// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using OtoEdit.Data.Context;

#nullable disable

namespace OtoEdit.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("OtoEdit.Data.Entities.ChatMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("EdlPatch")
                        .HasColumnType("jsonb")
                        .HasColumnName("edl_patch");

                    b.Property<string>("Mesaj")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("mesaj");

                    b.Property<DateTime>("OlusturmaTarihi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasColumnName("olusturma_tarihi")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("project_id");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("rol");

                    b.HasKey("Id");

                    b.HasIndex("OlusturmaTarihi")
                        .HasDatabaseName("idx_chat_messages_olusturma");

                    b.HasIndex("ProjectId")
                        .HasDatabaseName("idx_chat_messages_project_id");

                    b.ToTable("chat_messages", (string)null);
                });

            modelBuilder.Entity("OtoEdit.Data.Entities.EditDecisionList", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("EdlJson")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasDefaultValue("{}")
                        .HasColumnName("edl_json");

                    b.Property<DateTime?>("GuncellemeTarihi")
                        .HasColumnType("timestamptz")
                        .HasColumnName("guncelleme_tarihi");

                    b.Property<DateTime>("OlusturmaTarihi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasColumnName("olusturma_tarihi")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("project_id");

                    b.Property<int>("Versiyon")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1)
                        .HasColumnName("versiyon");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId")
                        .IsUnique()
                        .HasDatabaseName("idx_edl_project_id");

                    b.ToTable("edit_decision_lists", (string)null);
                });

            modelBuilder.Entity("OtoEdit.Data.Entities.EndpointLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<int>("DurationMs")
                        .HasColumnType("integer")
                        .HasColumnName("duration_ms");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)")
                        .HasColumnName("ip_address");

                    b.Property<string>("Method")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("method");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("path");

                    b.Property<string>("Query")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("query");

                    b.Property<string>("RequestBody")
                        .HasColumnType("text")
                        .HasColumnName("request_body");

                    b.Property<string>("ResponseBody")
                        .HasColumnType("text")
                        .HasColumnName("response_body");

                    b.Property<int>("StatusCode")
                        .HasColumnType("integer")
                        .HasColumnName("status_code");

                    b.Property<string>("TraceId")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("trace_id");

                    b.Property<string>("UserAgent")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("user_agent");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt")
                        .IsDescending()
                        .HasDatabaseName("idx_endpoint_logs_created_at");

                    b.HasIndex("Path")
                        .HasDatabaseName("idx_endpoint_logs_path");

                    b.HasIndex("StatusCode")
                        .HasDatabaseName("idx_endpoint_logs_status_code");

                    b.ToTable("endpoint_logs", (string)null);
                });

            modelBuilder.Entity("OtoEdit.Data.Entities.FunctionLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<long>("Id"));

                    b.Property<string>("ClassName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("class_name");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("ErrorCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("error_code");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("text")
                        .HasColumnName("error_message");

                    b.Property<string>("FilePath")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("file_path");

                    b.Property<string>("InputType")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("input_type");

                    b.Property<string>("InputValue")
                        .HasColumnType("text")
                        .HasColumnName("input_value");

                    b.Property<int>("LineNumber")
                        .HasColumnType("integer")
                        .HasColumnName("line_number");

                    b.Property<string>("MethodName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("method_name");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("Error")
                        .HasColumnName("severity");

                    b.Property<string>("StackTrace")
                        .HasColumnType("text")
                        .HasColumnName("stack_trace");

                    b.Property<string>("TraceId")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("trace_id");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt")
                        .IsDescending()
                        .HasDatabaseName("idx_function_logs_created_at");

                    b.HasIndex("ErrorCode")
                        .HasDatabaseName("idx_function_logs_error_code");

                    b.HasIndex("Severity")
                        .HasDatabaseName("idx_function_logs_severity");

                    b.ToTable("function_logs", (string)null);
                });

            modelBuilder.Entity("OtoEdit.Data.Entities.PipelineLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<long>("Id"));

                    b.Property<int>("Asama")
                        .HasColumnType("integer")
                        .HasColumnName("asama");

                    b.Property<DateTime>("BaslangicZamani")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasColumnName("baslangic_zamani")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTime?>("BitisZamani")
                        .HasColumnType("timestamptz")
                        .HasColumnName("bitis_zamani");

                    b.Property<string>("CiktiMetadata")
                        .HasColumnType("jsonb")
                        .HasColumnName("cikti_metadata");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Durum")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("durum");

                    b.Property<string>("GirdiMetadata")
                        .HasColumnType("jsonb")
                        .HasColumnName("girdi_metadata");

                    b.Property<string>("HataDetayi")
                        .HasColumnType("text")
                        .HasColumnName("hata_detayi");

                    b.Property<string>("HataMesaji")
                        .HasColumnType("text")
                        .HasColumnName("hata_mesaji");

                    b.Property<Guid?>("ProjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("project_id");

                    b.Property<Guid?>("RenderJobId")
                        .HasColumnType("uuid")
                        .HasColumnName("render_job_id");

                    b.Property<int?>("SureMs")
                        .HasColumnType("integer")
                        .HasColumnName("sure_ms");

                    b.Property<string>("TraceId")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("trace_id");

                    b.Property<Guid?>("VideoId")
                        .HasColumnType("uuid")
                        .HasColumnName("video_id");

                    b.HasKey("Id");

                    b.HasIndex("Asama")
                        .HasDatabaseName("idx_pipeline_logs_asama");

                    b.HasIndex("CreatedAt")
                        .IsDescending()
                        .HasDatabaseName("idx_pipeline_logs_created_at");

                    b.HasIndex("ProjectId")
                        .HasDatabaseName("idx_pipeline_logs_project_id");

                    b.HasIndex("VideoId")
                        .HasDatabaseName("idx_pipeline_logs_video_id");

                    b.ToTable("pipeline_logs", (string)null);
                });

            modelBuilder.Entity("OtoEdit.Data.Entities.Project", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Aciklama")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("aciklama");

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("ad");

                    b.Property<bool>("AudioEnhancementEnabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("audio_enhancement_enabled");

                    b.Property<int>("Durum")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("durum");

                    b.Property<bool>("GestureCommandsEnabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("gesture_commands_enabled");

                    b.Property<DateTime?>("GuncellemeTarihi")
                        .HasColumnType("timestamptz")
                        .HasColumnName("guncelleme_tarihi");

                    b.Property<DateTime>("OlusturmaTarihi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasColumnName("olusturma_tarihi")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid?>("TemplateId")
                        .HasColumnType("uuid")
                        .HasColumnName("template_id");

                    b.Property<int>("VideoFormati")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("video_formati");

                    b.HasKey("Id");

                    b.HasIndex("Durum")
                        .HasDatabaseName("idx_projects_durum");

                    b.HasIndex("OlusturmaTarihi")
                        .IsDescending()
                        .HasDatabaseName("idx_projects_olusturma");

                    b.HasIndex("TemplateId");

                    b.ToTable("projects", (string)null);
                });

            modelBuilder.Entity("OtoEdit.Data.Entities.RenderJob", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime>("BaslangicZamani")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasColumnName("baslangic_zamani")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTime?>("BitisZamani")
                        .HasColumnType("timestamptz")
                        .HasColumnName("bitis_zamani");

                    b.Property<string>("CiktiYolu")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("cikti_yolu");

                    b.Property<int>("Durum")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("durum");

                    b.Property<string>("EdlSnapshot")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("edl_snapshot");

                    b.Property<string>("HataMesaji")
                        .HasColumnType("text")
                        .HasColumnName("hata_mesaji");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("project_id");

                    b.Property<int?>("SureMs")
                        .HasColumnType("integer")
                        .HasColumnName("sure_ms");

                    b.HasKey("Id");

                    b.HasIndex("Durum")
                        .HasDatabaseName("idx_render_jobs_durum");

                    b.HasIndex("ProjectId")
                        .HasDatabaseName("idx_render_jobs_project_id");

                    b.ToTable("render_jobs", (string)null);
                });

            modelBuilder.Entity("OtoEdit.Data.Entities.Template", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("ad");

                    b.Property<bool>("AktifMi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("aktif_mi");

                    b.Property<string>("AltyaziFont")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("altyazi_font");

                    b.Property<string>("AltyaziRenk")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("altyazi_renk");

                    b.Property<string>("AltyaziStili")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("altyazi_stili");

                    b.Property<bool>("KonusmaciAdGoster")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("konusmaci_ad_goster");

                    b.Property<string>("LogoPozisyonu")
                        .HasColumnType("jsonb")
                        .HasColumnName("logo_pozisyonu");

                    b.Property<string>("LogoYolu")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("logo_yolu");

                    b.Property<DateTime>("OlusturmaTarihi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasColumnName("olusturma_tarihi")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Tanim")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("tanim");

                    b.Property<int>("VideoFormati")
                        .HasColumnType("integer")
                        .HasColumnName("video_formati");

                    b.HasKey("Id");

                    b.ToTable("templates", (string)null);
                });

            modelBuilder.Entity("OtoEdit.Data.Entities.Video", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Baslik")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("baslik");

                    b.Property<long>("DosyaBoyutu")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValue(0L)
                        .HasColumnName("dosya_boyutu");

                    b.Property<string>("DosyaYolu")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("dosya_yolu");

                    b.Property<int>("IslemDurumu")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("islem_durumu");

                    b.Property<DateTime?>("IslemTamamlanmaTarihi")
                        .HasColumnType("timestamptz")
                        .HasColumnName("islem_tamamlanma_tarihi");

                    b.Property<DateTime>("OlusturmaTarihi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasColumnName("olusturma_tarihi")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("project_id");

                    b.Property<TimeSpan?>("Sure")
                        .HasColumnType("interval")
                        .HasColumnName("sure");

                    b.Property<string>("TemizSesYolu")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("temiz_ses_yolu");

                    b.HasKey("Id");

                    b.HasIndex("IslemDurumu")
                        .HasDatabaseName("idx_videos_durum");

                    b.HasIndex("ProjectId")
                        .IsUnique()
                        .HasDatabaseName("idx_videos_project_id");

                    b.ToTable("videos", (string)null);
                });

            modelBuilder.Entity("OtoEdit.Data.Entities.VideoTranscript", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Dil")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasDefaultValue("tr")
                        .HasColumnName("dil");

                    b.Property<string>("HamMetin")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("ham_metin");

                    b.Property<int>("KelimeSayisi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("kelime_sayisi");

                    b.Property<DateTime>("OlusturmaTarihi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasColumnName("olusturma_tarihi")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("SttModel")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("stt_model");

                    b.Property<int>("SttSuresiMs")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("stt_suresi_ms");

                    b.Property<Guid>("VideoId")
                        .HasColumnType("uuid")
                        .HasColumnName("video_id");

                    b.Property<string>("ZamanDamgalari")
                        .HasColumnType("jsonb")
                        .HasColumnName("zaman_damgalari");

                    b.HasKey("Id");

                    b.HasIndex("VideoId")
                        .IsUnique()
                        .HasDatabaseName("idx_video_transcripts_video_id");

                    b.ToTable("video_transcripts", (string)null);
                });

            modelBuilder.Entity("OtoEdit.Data.Entities.ChatMessage", b =>
                {
                    b.HasOne("OtoEdit.Data.Entities.Project", "Project")
                        .WithMany("ChatMessages")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("OtoEdit.Data.Entities.EditDecisionList", b =>
                {
                    b.HasOne("OtoEdit.Data.Entities.Project", "Project")
                        .WithOne("EditDecisionList")
                        .HasForeignKey("OtoEdit.Data.Entities.EditDecisionList", "ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("OtoEdit.Data.Entities.PipelineLog", b =>
                {
                    b.HasOne("OtoEdit.Data.Entities.Project", "Project")
                        .WithMany("PipelineLogs")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("OtoEdit.Data.Entities.Video", "Video")
                        .WithMany("PipelineLogs")
                        .HasForeignKey("VideoId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Project");

                    b.Navigation("Video");
                });

            modelBuilder.Entity("OtoEdit.Data.Entities.Project", b =>
                {
                    b.HasOne("OtoEdit.Data.Entities.Template", "Template")
                        .WithMany("Projects")
                        .HasForeignKey("TemplateId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Template");
                });

            modelBuilder.Entity("OtoEdit.Data.Entities.RenderJob", b =>
                {
                    b.HasOne("OtoEdit.Data.Entities.Project", "Project")
                        .WithMany("RenderJobs")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("OtoEdit.Data.Entities.Video", b =>
                {
                    b.HasOne("OtoEdit.Data.Entities.Project", "Project")
                        .WithOne("Video")
                        .HasForeignKey("OtoEdit.Data.Entities.Video", "ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("OtoEdit.Data.Entities.VideoTranscript", b =>
                {
                    b.HasOne("OtoEdit.Data.Entities.Video", "Video")
                        .WithOne("Transcript")
                        .HasForeignKey("OtoEdit.Data.Entities.VideoTranscript", "VideoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Video");
                });

            modelBuilder.Entity("OtoEdit.Data.Entities.Project", b =>
                {
                    b.Navigation("ChatMessages");

                    b.Navigation("EditDecisionList");

                    b.Navigation("PipelineLogs");

                    b.Navigation("RenderJobs");

                    b.Navigation("Video");
                });

            modelBuilder.Entity("OtoEdit.Data.Entities.Template", b =>
                {
                    b.Navigation("Projects");
                });

            modelBuilder.Entity("OtoEdit.Data.Entities.Video", b =>
                {
                    b.Navigation("PipelineLogs");

                    b.Navigation("Transcript");
                });
#pragma warning restore 612, 618
        }
    }
}
